by *Alejandro Rojo* -- **linguistics - NLP - AI**

# Sintaxis de Python

Aquí se mencionarán cuestiones elementales de la sintaxis de Python.

# Caracteres que definen tipos de datos

Los corchetes `[]`, las llaves `{}` y los paréntesis `()` (estos últimos también establecen la preferencia de las operaciones) sirven para especificar diferentes tipos de datos, que aparecerán entre ellos y separados por comas:
+ `[a, ...]` lista
+ `(a, ...)` tupla
+ `{a, ...}` conjunto y `{a: a', ...}` diccionario

In [160]:
lista = [0, 1, None, 1, 0]
tupla = (0, 1, None, 1, 0)
conjunto =  {0, 1, None, 1, 0}
diccionario_indizado = {0: 0, 1: 1, 2: None, 3: 1, 4: 0}
diccionario_claves = {'es': 'casa', 'en': 'house', 'he': 'bayt'}

In [161]:
lista

[0, 1, None, 1, 0]

In [162]:
tupla

(0, 1, None, 1, 0)

In [163]:
conjunto

{0, 1, None}

In [164]:
diccionario_indizado

{0: 0, 1: 1, 2: None, 3: 1, 4: 0}

In [165]:
diccionario_claves

{'es': 'casa', 'en': 'house', 'he': 'bayt'}

## () Tuplas
Las tuplas son listas inmutables, que no admiten extensión, compárese el comportamiento de:

In [166]:
lista.append('nuevo')
lista

[0, 1, None, 1, 0, 'nuevo']

con el error en las tuplas:

In [167]:
tupla.append(2)
tupla

AttributeError: 'tuple' object has no attribute 'append'

## {:} Diccionario
La metáfora *diccionario* es clara: en un diccionario real encontramos pares {definido: definición}. Como puede observarse un diccionario es un conjunto de claves (por tanto son todas únicas) asociadas a un valor (estos no necesitan ser únicos ya).

Si queremos listar cada una de estas partes por separado hemos de usar los métodos `keys` y `values`:

In [168]:
list(diccionario_indizado.keys())

[0, 1, 2, 3, 4]

In [169]:
list(diccionario_indizado.values())

[0, 1, None, 1, 0]

In [170]:
list(diccionario_claves.keys())

['es', 'en', 'he']

In [171]:
list(diccionario_claves.values())

['casa', 'house', 'bayt']

Los diccionarios se utilizan para acceder a datos mediante un identificador `key` y para corresponder/mapear datos

# Sufijación

Las tuplas sufijadas a un identificador llaman a la función con sus elementos como argumentos:
`digits(...)`

In [172]:
def digits(number):
    return [int(cifra) for cifra in str(number)]

cifras = digits(12304005)
cifras

[1, 2, 3, 0, 4, 0, 0, 5]

Los corchetes sufijados a un identificador toman elementos de la lista, tupla, conjunto o diccionario (en este caso mediante sus claves)
`identificador[...]`

In [173]:
lista[0]

0

In [174]:
tupla[1]

1

Los conjuntos, sin embargo, no están ordenados, de aquí el siguiente error:

In [175]:
conjunto[2]

TypeError: 'set' object is not subscriptable

In [176]:
diccionario_indizado[0]

0

In [177]:
diccionario_claves['es']

'casa'

## ¿Cómo obtener varios elementos a la vez

Para ejemplificar algunos casos inicialicemos numpy y convirtamos la lista en un array

In [178]:
import numpy as np
lista_array = np.array(cifras)
lista_array

array([1, 2, 3, 0, 4, 0, 0, 5])

### Filtro

Si queremos aplicar una máscara, un filtro de valores de verdad, donde True indica que seleccionamos el elemento y False que lo descartamos, primero definimos el filtro como una lista de la misma longitud.

In [179]:
filtro = [True, True, False, False, False, False, False, True]

Una opción que usa una lista de comprensión es la siguiente:

In [180]:
[miembro for miembro, escogible in zip(cifras, filtro) if escogible]

[1, 2, 5]

pero con numpy es más sencillo:

In [181]:
lista_array[filtro]

array([1, 2, 5])

### Selección parcial

Podemos usar una lista de comprensión de tal manera que `map` sea implícito y la condición explícita:

In [201]:
[value for key, value in diccionario_claves.items() if key in ['es', 'en']]

['casa', 'house']

Podemos usar map y pasar como argumento el método `__getitem__()` que se aplicará a cada uno de los miembros

In [202]:
list(map(cifras.__getitem__, [0, 4, 2]))

[1, 4, 3]

In [203]:
list(map(diccionario_claves.__getitem__, ['es', 'en']))

['casa', 'house']

pero con numpy es más sencillo:

In [205]:
lista_array[[0, 4, 2]]

array([1, 4, 3])

### Selección continua

Si la selección es continua basta con definir el intervalo (el extremo superior es abierto y por ello el último índice no se incluye):

In [206]:
cifras[1:4]

[2, 3, 0]

o sin este atajo sintáctico:

In [207]:
cifras[slice(1, 4)]

[2, 3, 0]

# El punto, el directorio

> https://realpython.com/python-modules-packages/

Como quiera que los programas pueden hacerse muy complejos, se hace necesario [estructurarlos](https://en.wikipedia.org/wiki/Modular_programming): las funciones se definen en clases, estas son contenidas en módulos (archivos .py) y estas en paquetes (carpetas):

`función (< clase) < módulo < paquete`

Y así como una clase puede implementar el método de inicialización `__init__()`, en una carpeta puede haber un archivo `__init__.py` para inicializar el paquete.

En el ejemplo siguiente se busca obtener una representación textual de la fecha y tiempo actuales en UTC:

In [208]:
import datetime
datetime.datetime.utcnow().isoformat()

'2022-09-30T14:04:08.396564'

1. datetime es un módulo `datetime.py`
2. este contiene una clase homónima `datetime`
3. esta contiene un método `utcnow` que devuelve un objeto `time`
4. `isoformat`es otro método de `datetime` que devuelve una string del objeto anterior

# Indentación y estructura

¿por qué resulta tan cómodo y rápido prototipar con Python?
porque es bastante sucinto y minimalista

Este es un ejemplo de código en JavaScript:


```
var a = 10;
if (a > 20) {
    // bloque True
    haz_tal();
} else {
    // bloque False
    haz_cual();
}
```

Y este es el equivalente en Python:

```
a = 10
if a > 20:
    # bloque True
    haz_tal()
else:
    # bloque False
    haz_cual()
```

Como puede observarse, Python prescinde de diversos caracteres como `;`, `{}` y `()`.
1. En vez de usar `{}` para definir un bloque, agrupa las sentencias mediante su indentación común,
2. en vez de usar `()` para separar el valor boleano (resultado aquí de una comparación) de la siguiente sentencia o 
bloque utiliza : y retorno de línea.

En muchos lenguajes de programación diferentes de Python la **indentación** (la sangría, generada por el tabulador generalmente) es innecesaria pues ya existen otro elementos que determinan la estructura como `{}`. No obstante, se sigue usando pues conviene a la legibilidad del código.
La propuesta acertada de Python es hacer que deje de ser redundante y que determine directamente la estructura, reduciendo el número de elementos sintácticos.

El caracter `:` especifica un bloque (grupo de sentencias) a continuación que será identificado por incrementar su indentación. Dentro de cada bloque puede haber recursión con instrucciones que definan a su vez otros bloques.
Definen bloques `if, while, for, try, with` y las definiciones `def` y `class`. Véase https://docs.python.org/2/reference/compound_stmts.html

`if` puede considerarse una función de 3 argumentos if(booleano, bloque_true, bloque_false).
`elif` es azúcar sintáctico, siendo realmente una condición anidada dentro del bloque False pero que se utiliza para simplificar y hacer más legible la anidación de condiciones.

# Listas de comprensión

Obtengamos los números entre el 0 y el 19 (el extremo superior no se incluye, de aquí que usemos su incremento, el 20)

In [211]:
lista = range(0,20)
list(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

Si deseamos calcular los números pares (resto 0 de la división con 2) podemos realizarlo de la siguiente manera:

In [212]:
filter = [miembro for miembro in lista if miembro % 2 == 0]
filter

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

Las listas de comprensión `[<MAPEO> for _ in lista <FILTRO>]`, aunque se consideren más avanzadas, son alternativas compactas que facilitan la lectura de la intención del programador. Se usan como alternativa a bucles sencillos que realizan funciones filter y/o map.

En Javascript estos métodos han de explicitarse:

```
var lista = Array.from(Array(20).keys());
console.log(lista);

var mapeo = lista.map((x) => x % 2);
// 0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1

var filtro = lista.filter((x) => x % 2 == 0);
// 0,2,4,6,8,10,12,14,16,18
```

# Palabras reservadas
Son palabras que tienen una función asignada por python y son necesarias para su funcionamiento y por tanto no deben usarse

In [213]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']